services:
  mongo:
    container_name: movements-db_mongo
    image: mongo:5.0
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./database/movements.js:/docker-entrypoint-initdb.d/movements.js:ro

  redis:
    container_name: redis-server
    image: redis:7.0
    restart: always
    environment:
      - REDIS_PASSWORD=JYRS123
    ports:
      - "6379:6379"

